spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/shopping_cart?currentSchema=public'
    username: postgres
    password: 2210
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: 'sandbox.smtp.mailtrap.io'
    username: '46385d6c4cfd20'
    password: 'de0245c36dcf22'
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
           enable: true
